#!/bin/bash

# Advanced Label Management System (RepairGPT Inspired)
# 高度なラベル管理システム（RepairGPT に触発）

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_advanced() {
    echo -e "${PURPLE}[ADVANCED]${NC} $1"
}

# Function to create labels
create_label() {
    local name=$1
    local description=$2
    local color=$3
    
    if gh label create "$name" --description "$description" --color "$color" 2>/dev/null; then
        log_success "Advanced label created: $name"
    else
        log_warning "Label already exists or creation failed: $name"
    fi
}

# Check arguments
if [ "$#" -ne 2 ]; then
    log_error "Usage: $0 <owner> <repo>"
    log_info "Example: $0 username my-repo"
    exit 1
fi

OWNER=$1
REPO=$2

log_advanced "🔥 Advanced Label Management System Setup"
log_info "Repository: ${OWNER}/${REPO}"

# GitHub CLI authentication check
if ! gh auth status &> /dev/null; then
    log_error "GitHub CLI authentication required"
    log_info "Run: gh auth login"
    exit 1
fi

log_success "GitHub CLI authentication verified"

# Core Automation Labels (Basic)
log_info "📋 Creating Core Automation Labels"
create_label "claude-processed" "Claude Code processed" "1d76db"
create_label "claude-ready" "Ready for Claude automation" "0052cc"
create_label "automation-ready" "Ready for general automation" "0e8a16"
create_label "claude-completed" "Automation processing completed" "0e8a16"

# Advanced Automation Labels (RepairGPT Inspired)
log_info "🚀 Creating Advanced Automation Labels"
create_label "claude-auto-generated" "Automatically generated by Claude" "7057ff"
create_label "claude-full-automation" "Full automation workflow PR" "8b0000"
create_label "fully-automated" "100% automated processing" "ff4500"
create_label "smart-automation" "Smart automation processing" "ffd700"
create_label "ultimate-automation" "Ultimate automation processing" "8b0000"
create_label "lightning-processed" "Lightning fast processing" "ffff00"
create_label "ai-resolved" "Resolved by AI" "6f42c1"
create_label "zero-latency" "Zero latency processing" "ff1493"

# Tier-Specific Labels
log_info "⚡ Creating Tier-Specific Labels"
create_label "rapid-process" "Rapid automation tier" "ff6600"
create_label "ultimate-tier" "Ultimate automation tier" "8b0000"
create_label "smart-tier" "Smart automation tier" "32cd32"

# Priority Labels (Enhanced)
log_info "🎯 Creating Enhanced Priority Labels"
create_label "priority:critical" "Critical priority" "b60205"
create_label "priority:ultimate" "Ultimate priority" "8b0000"
create_label "priority:high" "High priority" "d93f0b"
create_label "priority:medium" "Medium priority" "fbca04"
create_label "priority:low" "Low priority" "0e8a16"

# Process Stage Labels
log_info "🔄 Creating Process Stage Labels"
create_label "stage:detection" "Issue detection stage" "c5def5"
create_label "stage:implementation" "Implementation stage" "fef2c0"
create_label "stage:review" "Review stage" "f9d0c4"
create_label "stage:merge" "Merge stage" "d4edda"
create_label "stage:cleanup" "Cleanup stage" "f8d7da"

# Quality Labels
log_info "✨ Creating Quality Labels"
create_label "quality:gold" "Gold standard quality" "ffd700"
create_label "quality:silver" "Silver standard quality" "c0c0c0"
create_label "quality:bronze" "Bronze standard quality" "cd7f32"

# Automation Performance Labels
log_info "📊 Creating Performance Labels"
create_label "perf:sub-minute" "Sub-minute processing" "ff1493"
create_label "perf:fast" "Fast processing" "ff6600"
create_label "perf:standard" "Standard processing" "32cd32"

# Special Feature Labels
log_info "🌟 Creating Special Feature Labels"
create_label "feature:auto-merge" "Auto-merge enabled" "7057ff"
create_label "feature:auto-close" "Auto-close enabled" "0e8a16"
create_label "feature:auto-delete" "Auto-delete branch" "d93f0b"
create_label "feature:intelligent" "Intelligent processing" "6f42c1"

# Context Labels
log_info "🎨 Creating Context Labels"
create_label "context:test" "Test automation" "c5def5"
create_label "context:production" "Production automation" "28a745"
create_label "context:experimental" "Experimental feature" "f66a0a"

log_advanced "🎉 Advanced Label Management System Complete!"

cat << 'EOF'

✅ Advanced Label System Created Successfully!

📊 Label Categories:
- 🔧 Core Automation: Basic processing labels
- 🚀 Advanced Automation: RepairGPT-inspired labels  
- ⚡ Tier-Specific: Ultimate/Rapid/Smart tiers
- 🎯 Enhanced Priority: Critical to low priorities
- 🔄 Process Stages: Detection through cleanup
- ✨ Quality Levels: Gold/Silver/Bronze standards
- 📊 Performance: Sub-minute to standard
- 🌟 Special Features: Auto-merge/close/delete
- 🎨 Context: Test/Production/Experimental

💡 Usage Examples:
- Issue: claude-processed + priority:ultimate + stage:detection
- PR: claude-auto-generated + fully-automated + perf:sub-minute
- Completed: claude-completed + quality:gold + ai-resolved

🚀 Your repository now has a comprehensive label management system!

EOF

log_success "🎯 Label management system deployment complete!"