name: Claude Code Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/claude-code-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Simple Test
      run: |
        echo "🤖 Claude Code Test Workflow Started"
        echo "Current time: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "✅ Test completed successfully"