name: Test Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Test GitHub Token
      run: |
        echo "Testing GitHub Token access..."
        curl -H "Authorization: token ${{ github.token }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/issues?state=open&per_page=1
    
    - name: Simple Script Test
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          console.log('GitHub Script Test Success');
          console.log('Repository:', context.repo);
          console.log('Event:', context.eventName);